### ISSUE TITLE
how to set menu display position left or right side ?

### ISSUE THREAD

**Issue by davamp** [abdulKarim002/SliderMenu#2]

**Comment by kodekarim** [comment]
you can set it from storyboard attribute inspector by selecting the navigation controller, check the example project for reference

<img width="1274" alt="screen shot 2017-03-22 at 10 44 48 am" src="https://cloud.githubusercontent.com/assets/13949425/24183167/a874eb7c-0eec-11e7-8eaa-3e88f9a1e675.png">

**Comment by davamp** [comment]
Yeah thanks man . You're the best . I will ask for more if I had more
questions. Have a nice day :)
